### ISSUE TITLE
Upgrade gorilla pkg version

### ISSUE THREAD

**Issue by fringlesinthestreet** [cloudinary/cloudinary-go#101]
## Describe the bug in a sentence or two.
Not a bug, just reporting that the current used github.com/gorilla/schema pkg version has a vulnerability, which is solved in version >=1.4.1: https://pkg.go.dev/vuln/GO-2024-2958

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [ ] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [X] Other (Vulnerability)

## Steps to reproduce

Using [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck)

## OS

- [X] Linux
- [ ] Windows
- [X] macOS
- [ ] Other (Specify)
- [ ] All

## Versions and Libraries (fill in the version numbers)

- Cloudinary Go SDK Version - 2.7.0
- GoLang Version - 1.21.0

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by Vdeub-cloudinary** [comment]
Thanks @fringlesinthestreet for the report, an internal ticket has been created to investigate this further

**Comment by Vdeub-cloudinary** [comment]
@fringlesinthestreet we release `2.9.0` where the gorilla package has now been upgraded.
