### ISSUE TITLE
mention go support for the docs main page

### ISSUE THREAD

**Issue by 1Shubham7** [cloudinary/cloudinary-go#107]
## Bug report for Cloudinary Go SDK
Before proceeding, please update to the latest version and test if the issue persists

## Describe the bug in a sentence or two.
…

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [ ] Behaviour - Functions are not working as expected (such as generate URL)
- [x] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce

Hey team Cloudinary, I was trying to use your service with go but when I went to your docs, in the main page there was no support for go. That led me to believe that you don't support go.  maybe that can be fixed : )

## Error screenshots

![image](https://github.com/user-attachments/assets/520b4f95-1218-4199-875d-de58762e774d)

Have a look a these options, maybe you can also add go here....

… if applicable

## OS

- [ ] Linux
- [ ] Windows
- [ ] macOS
- [ ] Other (Specify)
- [x] All

## Versions and Libraries (fill in the version numbers)

- Cloudinary Go SDK Version - 0.0.0
- GoLang Version - 0.0.0

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by tamaracloudinary** [comment]
Hi @1Shubham7,  

Yes, we do support Go! You can find the documentation here:  
https://cloudinary.com/documentation/go_integration  

Let me know if you're experiencing any issues.

**Comment by 1Shubham7** [comment]
> Hi @1Shubham7,
> 
> Yes, we do support Go! You can find the documentation here: https://cloudinary.com/documentation/go_integration
> 
> Let me know if you're experiencing any issues.

Yes, I did those docs, I just wanted to tell you people that you could also mention go on your main documentation examples (which is something that may confuse people  like me )  If you think otherwise, you can close the issue : )

**Comment by tamaracloudinary** [comment]
Hi @1Shubham7 
Thank you for bringing this to our attention, I've opened an internal ticket with our documentation team to have that included. 

I'll go ahead and close this issue for now, but please don’t hesitate to open a new one if you encounter any further issues or have any more feedback.

Best regards
