### ISSUE TITLE
NextCursor field in DeleteAssetsResult

### ISSUE THREAD

**Issue by stephenafamo** [cloudinary/cloudinary-go#23]
If I understand the [documentation](https://cloudinary.com/documentation/admin_api#delete_resources) correctly, a delete request could return `partial: true` **and** a `next_cursor` parameter which should be passed to another call to continue the delete operation.

As far as I can tell, the SDK does not return this `next_cursor` parameter. I think it should be added to the `DeleteAssetsResult` type.

**Comment by dannyv-cloudinary** [comment]
Hi Stephen.

Thanks for bringing this to our attention. I've raised this with the SDK development team who will address this in a future update.

Regards,
-Danny
