### ISSUE TITLE
Create signed request (signature)

### ISSUE THREAD

**Issue by odannyc** [cloudinary/cloudinary-go#33]
Feature request for Cloudinary Go SDK
…(If your feature is for other SDKs, please request them in the relevant repo)

## Explain your use case

- I need to generate a signature on the backend for the frontend to create a signed request

## Describe the problem you’re trying to solve

- https://cloudinary.com/documentation/upload_images#generating_authentication_signatures

## Do you have a proposed solution?

- The python lib exposes a similar method: https://github.com/cloudinary/pycloudinary/blob/9950c7e8af5036e4129f2c8f11e62e98163ee8de/cloudinary/utils.py#L577-L580

**Comment by odannyc** [comment]
After more digging of the code I found this:

https://github.com/cloudinary/cloudinary-go/blob/320ac57d59a12af4829096dd185ec0dbd7f8929b/api/api.go#L211-L224

Can I simply return that string to the frontend for them to use on a signed upload request?

**Comment by igy** [comment]
Hi Danny,

Yes, the output from that function should be a valid signature for a signed upload, and passing the signature string from the backend to the frontend is the same method we recommend for similar cases, like using our Javascript Upload Widget with signed upload where the signature comes from some backend code.

That said, the parameters sent on the API call must match the parameters used to create the signature, and the highlighted function is also setting the timestamp that's used on the request, so you need to pass the same timestamp to your frontend also and use it on the API call ( e.g. https://github.com/cloudinary/cloudinary-go/blob/3ea19ca02dff04344198e0b53091935edbc6d65b/api/uploader/upload.go#L103 where the timestamp used in teh signing function is added to the API call) 

If there's any problem with the signature you send on an API call, note that our error response shows the string we signed when checking the provided signature, so it's often easy to see why the signature didn't match

Thanks,
Stephen
