### ISSUE TITLE
Possible incorrect param for a function

### ISSUE THREAD

**Issue by stuartskelton** [cloudinary/cloudinary-go#34]
## Bug report for Cloudinary Go SDK
Before proceeding, please update to the latest version and test if the issue persists

## Describe the bug in a sentence or two

func (u *API) UpdateMetadata(ctx context.Context, params RenameParams) (*UpdateMetadataResult, error) {

Takes a  RenameParams I would have expected it take `type UpdateMetadataParams struct {`

Regards

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [X ] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce

Code search, 

## Error screenshots

… if applicable

## OS

- [ ] Linux
- [ ] Windows
- [ ] macOS
- [ ] Other (Specify)
- [X ] All

## Versions and Libraries (fill in the version numbers)

- Cloudinary Go SDK Version -Latest
- GoLang Version - Latest

## Repository

https://github.com/cloudinary/cloudinary-go/blob/3a4007e3a341968ff64e03b82789047bafd2a4c7/api/uploader/edit_asset.go#L109

**Comment by wissam-khalili** [comment]
Thank you for reporting this issue. An internal ticket was opened for this issue, though no ETA to share at the moment. We will update here with any progress.

**Comment by wissam-khalili** [comment]
Hi @stuartskelton
I would like to update you the issue was resolved .
Thanks,
Wissam

**Comment by stuartskelton** [comment]
thank you
