### ISSUE TITLE
Including Moderation in ExplicitResult (UploadResult).

### ISSUE THREAD

**Issue by TomerHacohen** [cloudinary/cloudinary-go#36]
I want to call "Explicit" method with moderation request for existing media, but I couldn't get the Moderation property in the response type.
```
res, err := cld.Upload.Explicit(ctx,
		uploader.ExplicitParams{
			PublicID:        publicId,
			Type:            "upload",
			ResourceType:    assetType,
			Moderation:      moderationMethod})
res.Moderation // not exists
```
I'd be happy if you'll extend "ExplicitResult" to include that.
Tomer

**Comment by strausr** [comment]
@TomerHacohen Thanks for reaching out. If you're trying to get the moderation status it is best to use the Admin API. Specifically AssetsByModeration. Please see the following for more information- https://cloudinary.com/documentation/webpurify_image_moderation_addon#image_moderation_queue

Please let us know if this answers your question

**Comment by TomerHacohen** [comment]
AssetsByModeration doesn't include the moderation labels, which exists in the REST API response for Explicit moderation request.
For Images, I want to get the response immediately as the REST API provides.
For videos, I actually want to verify that the process has begun and the status is `pending` without making another call.
