### ISSUE TITLE
Custom http.Client or http.RoundTripper

### ISSUE THREAD

**Issue by odannyc** [cloudinary/cloudinary-go#37]
Feature request for Cloudinary Go SDK

## Explain your use case
I need to be able to modify the http.RoundTripper or http.Client to add my own tracing/instrumentation.

## Do you have a proposed solution?
Expose a way to modify the `http.Client.Transport` via the Configuration that's passed into the client.

**Comment by roeeba** [comment]
Hi @odannyc, thanks for reaching out. I've opened an internal ticket for our engineers. We will share any updates once we'll have them.
