### ISSUE TITLE
cloudinary.NewFromURL does not work for custom domains

### ISSUE THREAD

**Issue by xorxsan** [cloudinary/cloudinary-go#58]
## Bug report for Cloudinary Go SDK

`cloudinary.NewFromURL` does not work for custom domains as it returns an instance of cloudinary where further operations return URLs that do not exist.

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce

```
package main

import (
	"context"
	"fmt"
	"github.com/cloudinary/cloudinary-go"
	"log"
)

func main() {
       // fake domain and publicId to showcase the issue
	cld, err := cloudinary.NewFromURL("https://cms.cloudinary.my-domain.com/image/upload/v1623180876/folder-1/folder-2/my-image.png")
	if err != nil {
		log.Fatalf("Failed to intialize Cloudinary, %v", err)
	}

	i, err := cld.Image("folder-1/folder-2/my-image")
	i.Transformation = "w_500"
	myURL, err := i.String()
	fmt.Println(myURL)
}
```
The above code prints this URL:
```
https://res.cloudinary.com/cms.cloudinary.my-domain.com/image/upload/w_500/v1/folder-1/folder-2/my-image?_a=AQAK9cJ
```
which returns 404.

## OS

- [ ] Linux
- [ ] Windows
- [ ] macOS
- [ ] Other (Specify)
- [x] All

## Versions and Libraries (fill in the version numbers)

- Cloudinary Go SDK Version - v1.7.0
- GoLang Version - go version go1.18.1 windows/amd64

**Comment by thomasgurung-cloudinary** [comment]
Hi,

You should pass `CLOUDINARY_URL` to cloudinary.NewFromURL("") which initialises your Go environment with the correct credentials to talk to our API. This URL can be found in your Dashboard.

If you are trying to set up a custom domain for your images, then you should add a `secure_cname` parameter to your `CLOUDINARY_URL`. 

So e.g.

` cld, err := cloudinary.NewFromURL("cloudinary://<api_key>:<api_secret>@<cloud_name>?secure_cname=my.cname.com")`

Hope this helps.
Thanks

**Comment by xorxsan** [comment]
Oh, thanks for the response. It was not clear from the documentation what the format was. Could you update the documentation and give this example?
Thanks!

**Comment by wissam-khalili** [comment]
Happy to see that it was helpful.
I will ask to update the documentation with the following examples as well.
Thanks!
