### ISSUE TITLE
Signing Parameters overwrites existing timestamp

### ISSUE THREAD

**Issue by LouisSayers** [cloudinary/cloudinary-go#62]
Following instructions on adding the [Media Upload widget](https://cloudinary.com/documentation/upload_images#using_cloudinary_backend_sdks_to_generate_sha_authentication_signatures)

It recommends using the `api.SignParameters` method to generate an upload signature.

Part of this signature is a timestamp - which is _generated in the frontend_ and needs to match the timestamp used to generate the signature.

However the code inside `api.SignParameters` will [overwrite any existing timestamp](https://github.com/cloudinary/cloudinary-go/blob/391442fec916379c4004ce113e31a6e60a67aed5/api/api.go#L249) given to it.

The result is that sometimes the signature will work (when processed with the same timestamp), and sometimes it won't work (if not processed within the same timestamp period).

This code needs to have a check to ensure that a timestamp doesn't already exist before adding one.

**Comment by thomasgurung-cloudinary** [comment]
Hi Louise,

Thanks for reporting this!

I have opened an internal bug for this so we will keep you posted on it.

Please do not hesitate to ask me any other questions or queries.

Kind Regards,
Thomas
