### ISSUE TITLE
Unable to download a zip archive of multiple files

### ISSUE THREAD

**Issue by sebas7dk** [cloudinary/cloudinary-go#66]
## Describe the bug in a sentence or two.
I try to download multiple images as a zip file. When I try the code below I receive the following error: **Missing public_ids**.
I contacted Cloudinary support and they verified that the golang code used for this library is not correct.

## Issue Type
-  Behaviour - Functions are not working as expected 

## Steps to reproduce
`
    var ids = api.CldAPIArray{}
    for _, up := range pr.Uploads {
        if up.Format == "jpg" {
            ids = append(ids, up.PublicID, up.Format)
        }
    }

    url, err := cl.Upload.DownloadZipURL(uploader.CreateArchiveParams{
        PublicIds:    ids,
        ResourceType: api.Image,
    })
    if err != nil {
        logrus.Fatal(err)
    }

    fmt.Println(url)`

## OS
- Linux

## Versions and Libraries
- Cloudinary Go SDK Version - 2.1.0
- GoLang Version - 1.18.5

**Comment by Vdeub-cloudinary** [comment]
@sebas7dk, I think this is an issue you already reported to us via support@cloudinary.com. I can confirm the team has a fix ready and will be part of the next version.

**Comment by sebas7dk** [comment]
@Vdeub-cloudinary, great thank you I'm looking forward to the next release.

**Comment by const-cloudinary** [comment]
@sebas7dk , the fix is released in the latest version: [2.2.0](https://github.com/cloudinary/cloudinary-go/releases/tag/v2.2.0)
