### ISSUE TITLE
NextCursor field in GetTransformationResult not being sent in response.

### ISSUE THREAD

**Issue by vivid-lukeloresch** [cloudinary/cloudinary-go#69]
## Bug report for Cloudinary Go SDK
Before proceeding, please update to the latest version and test if the issue persists

## Describe the bug in a sentence or two.
`NextCursor` is not sent in the reponse for [`admin.GetTransformation()`](https://github.com/cloudinary/cloudinary-go/blob/v2.2.0/api/admin/transformations.go#L67)

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [X] Behaviour - Functions are not working as expected (such as generate URL)
- [X] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce

When trying to get the list of derived images from a transform, we do not receive the `next_cursor` field in the response, so we can never get more derived images after the first call, even with `maxResults: 500`
```
	resp, err := cld.Admin.GetTransformation(
		context.TODO(),
		admin.GetTransformationParams{Transformation: t, MaxResults: 1},
	)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
    fmt.Printf("%+v\n", resp)
```

that call results in the following (url names have been removed)
```
&{Name:t_homepage_carousel_card_image AllowedForStrict:true Used:true Named:true Info:[map[crop:fill gravity:face height:390 width:312] map[radius:10]] Derived:[{PublicID:valid/path/1 ResourceType:image Type:upload Format:jpg URL:http://media.validurl SecureURL:https://media.validurl Bytes:11989 ID:xxx}] Error:{Message:}}
```
There are more than 500 derived images for this transformation, so we will need to be able to paginate these responses.

## OS

- [ ] Linux
- [ ] Windows
- [X] macOS
- [ ] Other (Specify)
- [ ] All

## Versions and Libraries (fill in the version numbers)

- Cloudinary Go SDK Version - 2.2.0
- GoLang Version - 1.17.2 darwin/amd64

**Comment by vivid-lukeloresch** [comment]
I would create a PR for this, but I can't seem to push to this repository.

**Comment by const-cloudinary** [comment]
@vivid-lukeloresch ,thank you for reporting the bug!
The fix in in the main branch and will be released in the next version.
