### ISSUE TITLE
Concurrency issue with analytics 

### ISSUE THREAD

**Issue by bradleyquinn140** [cloudinary/cloudinary-go#74]
## Bug report for Cloudinary Go SDK
Before proceeding, please update to the latest version and test if the issue persists

> I've looked at the code in this repository and the issue seems to still be there 

## Describe the bug in a sentence or two.

Analytics doesn't seem to be thread/concurrent safe. I'm not sure if this is deliberate, but seems like it could be an easy fix, since couldn't this initialization happen before the calls to `getKey`? https://github.com/cloudinary/cloudinary-go/blob/main/asset/analytics.go#L80

We use cloudinary to get images inside a graphql resolver, which means we use the cloudinary instance across threads. This can result in the stack trace below. 

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce

1. Create cloudinary instance
2. Create multiple goroutines which call `Image` 
3. Occasionally you may get this issue

## Error screenshots

```
﻿"/go/pkg/mod/github.com/cloudinary/cloudinary-go@v1.2.0/asset/asset.go:93 +0x3d8 fp=0xc0002008c8 sp=0xc0002005f0 pc=0xa522f8"
"github.com/cloudinary/cloudinary-go/asset.Asset.String(0xc7f706, 0x5, 0xc80d02, 0x6, 0xc0002df4f0, 0x9, 0x0, 0xc00013e230, 0x46, 0x0, ...)"
"/go/pkg/mod/github.com/cloudinary/cloudinary-go@v1.2.0/asset/asset.go:287 +0x38 fp=0xc0002005f0 sp=0xc000200588 pc=0xa537f8"
"github.com/cloudinary/cloudinary-go/asset.(*Asset).query(0xc0002008c8, 0x6, 0x6)"
"/go/pkg/mod/github.com/cloudinary/cloudinary-go@v1.2.0/asset/analytics.go:29 +0x62 fp=0xc000200588 sp=0xc0002004d8 pc=0xa511a2"
"github.com/cloudinary/cloudinary-go/asset.sdkAnalyticsSignature(0x82, 0x8)"
"/go/pkg/mod/github.com/cloudinary/cloudinary-go@v1.2.0/asset/analytics.go:71 +0x3dd fp=0xc0002004d8 sp=0xc000200408 pc=0xa517fd"
"github.com/cloudinary/cloudinary-go/asset.encodeVersion(0xc7f0ad, 0x5, 0x82, 0x3, 0x4, 0x40)"
"/go/pkg/mod/github.com/cloudinary/cloudinary-go@v1.2.0/asset/analytics.go:80 +0x190 fp=0xc000200408 sp=0xc000200360 pc=0xa51ae0"
"github.com/cloudinary/cloudinary-go/asset.getKey(0xc00013adc0, 0x6, 0x3, 0xc0002ecc30)"
"/usr/local/go/src/runtime/map_faststr.go:291 +0x3fe fp=0xc000200360 sp=0xc0002002f8 pc=0x412e9e"
"runtime.mapassign_faststr(0xb7b5a0, 0xc0000f91a0, 0xc0002df580, 0x6, 0x2)"
"/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0002002f8 sp=0xc0002002c8 pc=0x42dc02"
"runtime.throw(0xc8bb2b, 0x15)"
"goroutine 26 [running]:"
"fatal error: concurrent map writes"

```

## OS

- [x] Linux
- [ ] Windows
- [ ] macOS
- [ ] Other (Specify)
- [ ] All

## Versions and Libraries (fill in the version numbers)

- Cloudinary Go SDK Version - Issue appears to be in the latest version 
- GoLang Version - 1.19

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by aleksandar-cloudinary** [comment]
Hi, @bradleyquinn140 - Thanks for raising this. I'll create an internal ticket with our SDK team who'll be able to assist with this.

**Comment by const-cloudinary** [comment]
@bradleyquinn140 thanks for reporting the issue!
The fix is merged and will be released in the next version.

**Comment by bradleyquinn140** [comment]
Thankyou @const-cloudinary @aleksandar-cloudinary
