### ISSUE TITLE
Context metadata is unavailable from admin.SearchAsset

### ISSUE THREAD

**Issue by markraymondlush** [cloudinary/cloudinary-go#83]
## Explain your use case

I would like to access the context metadata from an asset after calling `(*admin.API).Search`.

In my particular use-case, I want to access the alt text of an asset.

## Describe the problem you’re trying to solve

The context metadata is not returned as part of a member of the `admin.SearchAsset`. The only way of getting the data out with the code as-is is by unmarshaling the `SearchResult.Response` field (which is an `interface{}`) into a custom data structure, which is error-prone.

## Do you have a proposed solution?

The easier way of handling this would be to add a new field called `ContextMetadata ContextMetadataResult` which contains the metadata context as a `map[string]string`. This is consistent with the current way other pieces of metadata are returned (e.g., `ImageMetadata ImageMetadataResult`).

**Comment by Vdeub-cloudinary** [comment]
@markraymondlush that's a good catch :) 
I have raised this with our SDK team to support this.
