### ISSUE TITLE
Add support for `PlaybackURL` in `UploadResult` on video upload

### ISSUE THREAD

**Issue by const-cloudinary** [cloudinary/cloudinary-go#87]
Feature request for Cloudinary Go SDK

When uploading a video file the result contains `playback_url` field which is currently not exposed in Cloudinary Go SDK.

## Do you have a proposed solution?

Add `PlaybackURL` field to [UploadResult](https://github.com/cloudinary/cloudinary-go/blob/74b7a5291c66ecc64545b170b5fbb7c197fc7a15/api/uploader/upload_asset.go#L199)

**Comment by Suraj3240** [comment]
Hey, I went through the code and came up with this.
![image](https://github.com/cloudinary/cloudinary-go/assets/105744567/cba2c634-2198-4031-a050-c859822e5a7b)
Here I have added the `PlaybackURL` field to the `UploadResult` struct.

![image](https://github.com/cloudinary/cloudinary-go/assets/105744567/eebacb6c-c1c9-4e4e-ae4d-014abca7b43e)
Here I have modified the `Upload` function which will parse the `playback_url` field from the Cloudinary API response and assign it to the `PlaybackURL` field in the `UploadResult` struct.


So if you think that these changes will solve the issue, so please assign me this issue, I will commit the changes and then will raise a PR.

**Comment by wissam-khalili** [comment]
Hi @const-cloudinary, could you please check the above request?
Thanks!

**Comment by const-cloudinary** [comment]
@Suraj3240 thank you for looking into it!
The change on the first screenshot should be enough.
But instead of adding it at the end, it would make more sense to put it on line 204, right after `SecureURL`

**Comment by Suraj3240** [comment]
@const-cloudinary I have raised a PR. Can you check it?

**Comment by const-cloudinary** [comment]
@Suraj3240 reviewed your PR, please fix a few minor issues.
