### ISSUE TITLE
Add Access Control to UploadParams

### ISSUE THREAD

**Issue by ncunningham-stairsupplies** [cloudinary/cloudinary-go#99]
## Describe the bug in a sentence or two.
uploader.UploadParams is missing the optional `AccessControl` field that is present in the api documentation [Api Link](https://cloudinary.com/documentation/image_upload_api_reference#upload_optional_parameters)

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [ ] Behaviour - Functions are not working as expected (such as generate URL)
- [X] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Versions and Libraries (fill in the version numbers)

- Cloudinary Go SDK Version - 2.7.0
- GoLang Version - 1.21.7

**Comment by Vdeub-cloudinary** [comment]
Hi @ncunningham-stairsupplies, effectively the `AccessControl` is missing [here](https://github.com/cloudinary/cloudinary-go/blob/v2.7.0/api/uploader/upload_asset.go#L16). I'll raise to the team but in the meantime, you could use an upload preset and set the `AccessControl` via this preset.
